# Generated by Django 5.1 on 2024-09-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_visit_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='client_name',
            new_name='name',
        ),
    ]
